apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qujrh4drr-go
  janus-idp.io/tekton: qujrh4drr-go
  backstage.io/kubernetes-id: qujrh4drr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qujrh4drr-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
